"""
Django settings for InformationCollector project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-9-em27$c02rul=id9k(j5roty_!qk@wkgbzx+xp8hk_pir3j4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if 'OPENSHIFT_POSTGRESQL_VERSION' in os.environ:
    DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # plugins
    'bootstrapform',
    'debug_toolbar',
    'django_gravatar',
    'django.contrib.humanize',
    # apps
    'core',
)
if not DEBUG:
    INSTALLED_APPS = INSTALLED_APPS + ('raven.contrib.django.raven_compat', )

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'InformationCollector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InformationCollector.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

}

if not DEBUG:
    import dj_database_url

    database_url_config = dj_database_url.config(env='OPENSHIFT_POSTGRESQL_DB_URL')
    database_url_config['NAME'] = 'python'
    DATABASES['default'] = database_url_config

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.environ.get('OPENSHIFT_DATA_DIR', BASE_DIR), 'media')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/bower_components"),
    os.path.join(BASE_DIR, "static/"),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'wsgi', 'static')

AUTH_USER_MODEL = 'core.Member'
LOGIN_URL = 'core:login'

# Django debug toolbar
DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': '',
}

# Raven
if not DEBUG:
    import raven

    RAVEN_CONFIG = {
        'dsn': 'https://b32f63a912054d01b45a48a515a50fcd:8b46738c65194064a0dc01547b5c8a18@sentry.nivad.io/3',
        'release': raven.fetch_git_sha(os.path.dirname(os.path.dirname(__file__))),
    }
